"""
Configuration API Endpoints
Save and manage IAM configuration
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict
import os

router = APIRouter(prefix="/api/iam", tags=["Configuration"])


class ConfigureRequest(BaseModel):
    provider: str  # 'okta' or 'entra_id'
    config: Dict[str, str]


@router.post("/configure")
async def configure_iam(request: ConfigureRequest):
    """
    Save IAM configuration
    This writes to a .env file that needs to be loaded on restart
    """
    try:
        env_file_path = os.getenv("ENV_FILE_PATH", "/app/.env")

        # Read existing .env file
        existing_env = {}
        if os.path.exists(env_file_path):
            with open(env_file_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        existing_env[key.strip()] = value.strip()

        # Update with new values
        existing_env.update(request.config)

        # Write back to .env file
        with open(env_file_path, 'w') as f:
            f.write("# IAM Configuration\n")
            f.write("# Generated by AI Governance Platform\n\n")

            for key, value in existing_env.items():
                f.write(f"{key}={value}\n")

        return {
            "success": True,
            "message": f"{request.provider} configuration saved",
            "restart_required": True
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save configuration: {str(e)}")


@router.get("/config/{provider}")
async def get_config(provider: str):
    """
    Get current configuration for a provider (without secrets)
    """
    if provider == "okta":
        return {
            "provider": "okta",
            "configured": bool(os.getenv("OKTA_DOMAIN")),
            "domain": os.getenv("OKTA_DOMAIN", ""),
            "client_id": os.getenv("OKTA_CLIENT_ID", "")[:8] + "..." if os.getenv("OKTA_CLIENT_ID") else "",
            "has_secret": bool(os.getenv("OKTA_CLIENT_SECRET")),
            "has_api_token": bool(os.getenv("OKTA_API_TOKEN"))
        }
    elif provider == "entra_id":
        return {
            "provider": "entra_id",
            "configured": bool(os.getenv("ENTRA_TENANT_ID")),
            "tenant_id": os.getenv("ENTRA_TENANT_ID", ""),
            "client_id": os.getenv("ENTRA_CLIENT_ID", "")[:8] + "..." if os.getenv("ENTRA_CLIENT_ID") else "",
            "has_secret": bool(os.getenv("ENTRA_CLIENT_SECRET"))
        }
    else:
        raise HTTPException(status_code=400, detail="Unknown provider")
